spring.application.name=blockchain
# Puerto del nodo (cada integrante del grupo usa uno diferente)
server.port=8080

# Dificultad del Proof of Work (cantidad de ceros al inicio del hash)
blockchain.difficulty=3
blockchain.seed-url=http://172.22.49.195:8080
blockchain.my-url=http://172.22.49.195:8080