spring.application.name=blockchain
server.port=8080

blockchain.difficulty=4
blockchain.seed-peers=http://127.0.0.1:8080
blockchain.my-url=http://127.0.0.1:8080

blockchain.block-reward=10
blockchain.auto-mine-threshold=3

blockchain.wallet.private-key=9f29ac941723135683d45873a8e4eb3c5348cc5a19efe94283c5be9937717c0f