spring.application.name=blockchain
server.port=8081

blockchain.difficulty=4
blockchain.seed-peers=http://127.0.0.1:8080
blockchain.my-url=http://127.0.0.1:8081

blockchain.block-reward=10
blockchain.auto-mine-threshold=3

blockchain.wallet.private-key=a469c76101eb0cd582b7670ed21aeae7463c945d61f93b5aef5c88f7816cb55f