spring.application.name=blockchain
server.port=8082

blockchain.difficulty=4
blockchain.seed-peers=http://127.0.0.1:8080
blockchain.my-url=http://127.0.0.1:8082

blockchain.block-reward=10
blockchain.auto-mine-threshold=3

blockchain.wallet.private-key=0ee57ff574734b5f420edee41d937133e8970b92e56408c3cb390952606fef35